---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: release-dir
  - name: istio-release

outputs:
  - name: release-tarball

run:
  path: istio-release/ci/tasks/create-release-tarball/task

params:
  RELEASE_DIR: release-dir
