---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline
inputs:
- name: istio-release
- name: master-dir
params:
  GIT_COMMIT_EMAIL:
  RELEASE_BRANCH:
outputs:
- name: merged-branch
run:
  path: istio-release/ci/tasks/merge-branch-to-master/task
